
/*
 * Generated by NK-CPP
 */
#include <spdlog/spdlog.h>
#include "ITargetState.idl.hpp"

trafficlight::ITargetState::ITargetState(NkKosTransport *transport, nk_iid_t riid) : transport(transport), riid(riid) {
}

trafficlight::ITargetState::ITargetState(NkKosTransport *transport, const char *endpoint_name) : transport(transport) {
    riid = ServiceLocatorGetRiid(transport->handle, endpoint_name);
    if (INVALID_RIID == riid) {
        spdlog::error("Service RIID {} not found", endpoint_name);
    }
}

const trafficlight_ITargetState_NotifyCurrentState_res *
trafficlight::ITargetState::NotifyCurrentState(nk_uint8_t id, nk_uint32_t mode) {
    trafficlight_ITargetState_NotifyCurrentState_req req{
            {}, id, mode
    };
    static trafficlight_ITargetState_NotifyCurrentState_res res{};
    reqArena.reset();
    resArena.reset();
    nk_req_reset(&req);
    nk_req_reset(&res);
    nk_msg_set_method_id(
            &req,
            this->riid,
            trafficlight_ITargetState_NotifyCurrentState_mid
    );
    nk_msg_set_method_id(
            &res,
            this->riid,
            trafficlight_ITargetState_NotifyCurrentState_mid
    );
    nk_msg_set_ncaps(
            &req,
            trafficlight_ITargetState_NotifyCurrentState_req_handles
    );
    nk_msg_set_ncaps(
            &res,
            trafficlight_ITargetState_NotifyCurrentState_res_handles
    );
    nk_err_t rc = nk_transport_call(
            &this->transport->base,
            &req.base_,
            nullptr,
            &res.base_,
            nullptr
    );

    return &res;
}
