package trafficlight.IDiagnostics

struct DirectionColor {
    UInt8 r;
    UInt8 y;
    UInt8 g;
}

typedef UInt32 ModeType;
typedef UInt32 MeasuredCurrent;
typedef sequence<MeasuredCurrent, 3> LightsMeasuredCurrent;

interface {
    NotifyFailure(in string<20> severity, in UInt8 id, in ModeType requested, in DirectionColor problem);
    NotifyState(in UInt8 id, in LightsMeasuredCurrent measured, in ModeType mode);
}
