package trafficlight.ILightMode

typedef UInt32 ModeType;
const ModeType ModeRed    = 1;
const ModeType ModeYellow = 2;
const ModeType ModeGreen  = 4;
const ModeType ModeBlink  = 16;

typedef ModeType DirectionMode;

struct CrossedDirectionsMode {
    DirectionMode dir0;
    DirectionMode dir1;
}

interface {
    SetMode(in CrossedDirectionsMode mode);
}
