
/*
* Generated by NK-CPP
*/
#ifndef TRAFFICLIGHT_ITARGETSTATE_IDL_HPP
#define TRAFFICLIGHT_ITARGETSTATE_IDL_HPP

#include <coresrv/sl/sl_api.h>
#include <coresrv/nk/transport-kos.h>
#include <rtl/string.h>
#include <string>
#include <vector>
#include "trafficlight/ITargetState.idl.h"
#include "XNkArena.hpp"

namespace trafficlight {
    using std::vector;

    class ITargetState {
    private:
        NkKosTransport *transport;
        nk_iid_t riid;
        XNkArena<trafficlight_ITargetState_req_arena_size> reqArena;
        XNkArena<trafficlight_ITargetState_res_arena_size> resArena;
    public:

        using ModeType = trafficlight_ITargetState_ModeType;

        struct NotifyCurrentStateResponse {
            nk_err_t status;

        };

        ITargetState(NkKosTransport *transport, nk_iid_t riid);

        ITargetState(NkKosTransport *transport, const char *endpoint_name);

        nk_err_t NotifyCurrentState(nk_uint8_t in_id, nk_uint32_t in_mode);
    };
};
#endif //TRAFFICLIGHT_ITARGETSTATE_IDL_HPP
